services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DATASOURCE_DB}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    networks:
      - app-net

  backend:
    build:
      context: ./ECOMMERCE-SOFTWARE-S
      dockerfile: Dockerfile
    image: santiagoinf/backend-s
    container_name: backend-s
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USER: ${DATASOURCE_USER}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_CLIENT_SECRET: ${PAYPAL_CLIENT_SECRET}
      PAYPAL_MODE: ${PAYPAL_MODE}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - app-net

  frontend:
    build:
      context: ./fontend-react  # Cambia esto a la carpeta real de tu frontend
      dockerfile: Dockerfile
    image: frontend-s
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - "${FRONTEND_HOST_PORT}:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge







